### ISSUE TITLE
Fix documentation page for mobile devices

### ISSUE THREAD

**Issue by binste** [altair-viz/altair#2775]
See https://github.com/altair-viz/altair/pull/2755#issuecomment-1366574385

@mattijn I'll look into it. Probably need to make the `max-width` of the sidebar in `custom.css` dependent on the device. It's currently set to a constant `20%`.

```css
.bd-sidebar-primary {
  max-width: 20%
}
```
